name: my_library
description: A new Flutter library project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  fluent_ui: any
  macos_ui: any
  yaru: any
  chicago: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

